version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js", "-m", "8222", "-p", "4222"]
    ports:
      - "4222:4222"
      - "8222:8222"
  nats2:
    image: nats:2.10
    command: ["-js", "-m", "8222", "-p", "4222"]
    ports:
      - "4223:4222"
      - "8223:8222"
  api:
    image: node:20-alpine
    working_dir: /app
    network_mode: host
    environment:
      PORT: 4000
      CLUSTERS_FILE: /app/clusters.json
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - nats
      - nats2
  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      - VITE_API_BASE=http://localhost:4000
    volumes:
      - ./web:/app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

  # Phase A: Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.retention.time=7d"
    ]
    # Prometheus will be at http://localhost:9090

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # Grafana will be at http://localhost:3000 (change password after first login)
