version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js", "-m", "8222", "-p", "4222"]
    ports:
      - "4222:4222"
      - "8222:8222"
  nats2:
    image: nats:2.10
    command: ["-js", "-m", "8222", "-p", "4222"]
    ports:
      - "4223:4222"
      - "8223:8222"
  api:
    image: node:20-alpine
    working_dir: /app
    network_mode: host
    environment:
      PORT: 4000
      NATS_CLUSTERS: |
        [
          {
            "key": "local-docker",
            "label": "Local (docker)",
            "natsUrl": "nats://localhost:4222",
            "monitorUrl": "http://localhost:8222"
          },
          {
            "key": "local-docker-2",
            "label": "Local 2 (docker)",
            "natsUrl": "nats://localhost:4223",
            "monitorUrl": "http://localhost:8223"
          },
          {
            "key": "demo",
            "label": "demo.nats.io",
            "natsUrl": "nats://demo.nats.io:4222",
            "monitorUrl": "http://demo.nats.io:8222"
          },
          {
            "key": "ilv2-prod",
            "label": "ILV2 PROD NATS CLUSTER (tunnel)",
            "natsUrl": "nats://localhost:14222",
            "monitorUrl": "http://localhost:18222"
          },
          {
            "key": "ilv2-staging",
            "label": "ILV2 STAGING NATS CLUSTER (tunnel)",
            "natsUrl": "nats://localhost:24222",
            "monitorUrl": "http://localhost:28222"
          },
          {
            "key": "ilv2-dev",
            "label": "ILV2 DEV NATS CLUSTER (tunnel)",
            "natsUrl": "nats://localhost:34222",
            "monitorUrl": "http://localhost:38222"
          }
        ]
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - nats
      - nats2
  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      - VITE_API_BASE=http://localhost:4000
    volumes:
      - ./web:/app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api
